#!/usr/bin/env bash
set -o errexit

DOMAIN=${1:-magento237.multisfepay.io}

curl -s https://raw.githubusercontent.com/multisafepay/docker-magento/master/lib/template | bash

bin/download community 2.3.7 \
  && bin/setup "${DOMAIN}"
